IOP_BIN = libntfs_example.elf
IOP_OBJS = main.o

IOP_LIBS = -lkernel -lntfs
IOP_INCS = -I$(PS2SDK)/iop/include

all: $(IOP_BIN)

include $(PS2SDK)/Defs.make
include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal